### PR TITLE
issue-348 : fixed a few bugs related to regard-application

### LINKED ISSUE #348: Control Construct of regarded application should be stored in elastic search.
**Problem Description:**

When we trigger /v1/regard-application , it will send a callback /v1/redirect-topology-change-information to regarded application with it's own details. 

The response of /v1/redirect-topology-change-information will contain the control construct of regarded application. This response(control construct) should be updated in the elastic search.

### PR DESCRIPTION
**Pull request by DanaSunal**
Fixes #348

### CODE REVIEW

**Comment by DanaSunal** [comment]
Merge first openBackhaul/ApplicationPattern#732 .
Reviewer is @vanithavalluripalli9

**Review by vanithavalluripalli9 — CHANGES_REQUESTED** [review]
Thank you for the changes . 

Changes looks good . But , We can observe that if we regard ALT application , the control construct is not being stored in elastic search it is because of the check we made in line no:804 in version 1 because of the issue https://github.com/openBackhaul/ApplicationLayerTopology/issues/4 . 

According to understanding this is not required in v2.0.1 anymore as we separated application data and config data. @PrathibaJee could you please confirm on the same.

**Comment by PrathibaJee** [comment]
@vanithavalluripalli9  , thanks for the keen observation. Raised a separate issue for this https://github.com/openBackhaul/ApplicationLayerTopology/issues/358. We shall proceed further to merge the changes in this pull request.

**Review by MartinSunal — APPROVED** [review]

**Comment by vanithavalluripalli9** [comment]
Reverting the changes as the dependent pull request
 https://github.com/openBackhaul/ApplicationPattern/pull/732  have comments and yet to be merged .

**Pull request merged**
